### ISSUE TITLE
[Bug]: Incorrect Redirection and "Page Not Found" Error When Creating Subnet with Default VPC in Add Server Flow

### ISSUE THREAD

**Issue by pvdevs** [devopness/devopness#1012]
### Problem: What is happening?

When attempting to create a new server and selecting "Create New Subnet," the following issues occur:
1. **Incorrect Redirection**: Instead of being directed to the subnet creation flow, the user is redirected to a pipeline flow.
2. **"Page Not Found" Error**: If the VPC selected is the default, the user encounters a "Devopness could not find the page you are looking for" error.

Here's a video of the unexpected behavior:
1- Cenario where you select a custom Network

https://github.com/user-attachments/assets/5de9737f-98f3-4536-b6f1-2eb989276452

2- Cenario where you select the default Network

https://github.com/user-attachments/assets/9dd61783-ea27-4cbe-be08-a980c6117eba

### Expected behavior

Upon choosing to create a new subnet within the server creation flow, the user should be redirected to the subnet creation flow without encountering errors. Additionally, selecting the default VPC should not result in a "Page Not Found" error.

### Steps to reproduce

1. On Devopness, navigate to a project then select an environment
2. Find the Servers card
3. Click View in the Servers card to see a list of existing Servers
4. On the upper-right corner of the list click **ADD SERVER**
5. On "Create or connect a Server", select a Cloud Provider (in my case, it was AWS)
6. Select your credentials, then click **NEXT**
7. On second step:
     - To see the error of pipeline redirection, choose a custom Network, and on Subnet, click on "Create a new Subnet"
     - To see the error of page not found, choose the default Network, and on Subnet, click on "Create a new Subnet"
8. After that, you should see the expected error

### Which Devopness module(s) are the source of the bug?

Devopness web app

### Additional details

**Browser Version**: Google Chrome 129.0.6668.100

**Comment by thlmenezes** [comment]
Thanks for the bug report @pvdevs 

Adding more information to the bugs

### Incorrect Redirection

> To see the error of pipeline redirection, choose a custom Network, and on Subnet, click on "Create a new Subnet"

The expected URL should end with "subnets/add"

EXPECTED: https://app.devopness.com/projects/276/environments/412/networks/25/subnets/add

GOT: https://app.devopness.com/projects/276/environments/412/networks/25/add

### "Page Not Found" Error

> To see the error of page not found, choose the default Network, and on Subnet, click on "Create a new Subnet"

When selecting Network "default", user should not see option "Create a new Subnet"

**Comment by thlmenezes** [comment]
@pvdevs bug fixed and deployed to production.

### Incorrect Redirection

✅ The expected URL should end with "subnets/add"

![image](https://github.com/user-attachments/assets/b0b61418-ea61-4933-bc2d-4cb61dac7459)

![image](https://github.com/user-attachments/assets/272d601c-0663-42d0-abfd-ef418508626c)


### "Page Not Found" Error

✅ When selecting Network "default", user should not see option "Create a new Subnet"

![image](https://github.com/user-attachments/assets/ba27cbb8-2387-48f6-9e5a-40065554747e)

Thanks for reporting
