### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by brunoro** [devopness/devopness#16]
**Describe the solution you'd like**
Include a mechanism to specify the API version used by the SDK.

The default API version would be the latest, but users would be able to specify a previous version. This would be specially useful to maintain backwards compatibility, at least on a reasonable timeframe for users to update their code.

**Describe alternatives you've considered**
Including this feature later, when a breaking API version comes along.

**Comment by danielSbastos** [comment]
Hi @JeffersonAbreu, @jfoliveira and @vianaz! I'd like to take on this issue. Is there any new information from when the issue was created until now? Also, is the solution a theoretical one, or would it be prefered to include an actual implementation?

**Comment by jfoliveira** [comment]
Hello @danielSbastos! 👋
Welcome to Devopness open source projects!

Thanks for your interest in giving contributions to our project!
This issue depends on changes on our API so it cannot be implemented on the SDK only.

In the meantime, would you be willing to start your contributions to this repository by working on simpler issues such as #25 or contributing with improvements to Devopness documentation?

Hope you have a great time contributing and learning around here! 😄

**Comment by jfoliveira** [comment]
Closing, as this is not high priority for not being a real pain point for users at the moment.
