### ISSUE TITLE
Define onTokenExpired event

### ISSUE THREAD

**Issue by jfoliveira** [devopness/devopness#25]
**Is your feature request related to a problem? Please describe.**

Currently SDK users need to implement a token refresh process if they want to keep a user logged in. This works fine, but could be easier for SDK users when a token expired, as token expiration HTTP 401 may require some logic to be differentiated from regular HTTP 401 status code.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Check for HTTP status code equals 401 and send a token refresh request.

Pseudo-code, yet to be tested:
```typescript
    public onTokenExpired: () => void;

    public tokenExpired(): void {
        if (this.onTokenExpired) {
            this.onTokenExpired();
        }
    }
```

**Additional context**

The responsibility on making the decision of refreshing a token or not doesn't change. It'll still be up to the SDK consumer to decide what to do. 
We just want to assume the logic that will check the `HTTP 401 Unauthorized` response to tell which ones are related to token expiration and notify the client app.

**Comment by danielSbastos** [comment]
Hi, @jfoliveira!
I just wanted to make sure I understood correctly the issue. Currently, the SDK exports a [`refreshTokenUser`](https://github.com/devopness/devopness/blob/f08cfd87d9fac380e844513787da6f7ea05fd5e0/packages/sdks/javascript/src/api/generated/apis/users-api.ts#L169C18-L180) function. For any API request, the conditional as to whether the 401 is for an expired token or an unauthorized request is still being done client-wise, right? Therefore, this implementation would differentiate the two 401s, and, for example, for a given response, maybe add in the [axios response intercept](https://github.com/devopness/devopness/blob/f08cfd87d9fac380e844513787da6f7ea05fd5e0/packages/sdks/javascript/src/services/ApiBaseService.ts#L95-L113) an error?

**Comment by jfoliveira** [comment]
> Therefore, this implementation would differentiate the two 401s

Correct.

> for example, for a given response, maybe add in the axios response intercept

That could be a starting point.
The most important criteria is that a client application consuming this SDK, when [initializing an instance of Devopness API client](https://github.com/devopness/devopness/blob/main/packages/sdks/javascript/README.md#initializing) should be able to provide a callback to be invoked once the `tokenExpired` event is dispatched.

Example, pseudo code from a user consuming Devopness SDK-JS and logging the event to the console:
```ts
import { DevopnessApiClient } from '@devopness/sdk-js'

// 1) consumer initialize DevopnessApiClient instance 
const devopnessApi = new DevopnessApiClient();

// 2) consumer defines its own event handler for the`onTokenExpired` event:
public doThisWhenDevopnessTriggerTokenExpiredEvent(): void {
  console.log('Devonpess `tokenExpired` event has been triggered.');
}

// 3) consumer tells client instance to invoke a custom method when the event is triggered:
devopnessApi.onTokenExpired = doThisWhenDevopnessTriggerTokenExpiredEvent;

// any other code interacting with Devopness SDK:
const userTokens = await devopnessApi.users.loginUser(...)

```


Then, on the SDK itself, we could check if the consumer defined an event handler and - if so - we trigger the externally defined method:
```ts
    public onTokenExpired: () => void;

    public tokenExpired(): void {
        if (this.onTokenExpired) {
            this.onTokenExpired();
        }
    }
```

Let us know if you have further questions.
