### ISSUE TITLE
Improve example code on how to consume this SDK

### ISSUE THREAD

**Issue by jfoliveira** [devopness/devopness#7]
**Is your feature request related to a problem? Please describe.**

Improve the sample source code provided for first time users of this SDK.

**Describe the solution you'd like**

Make it easier for users to understand how to consume this package in the most common scenarios:
- CLI: Node.js
- Server side: Node.js
- Browser, from CDN: Javascript
- Browser, from NPM: Javascript
- Browser, from NPM: Typescript with Parcell or webpack

**Describe alternatives you've considered**

Use codesandbox.io, runkit.com or related tools that allow running the sample code online.

**Additional context**

**Comment by brunoro** [comment]
Error handling examples:
* async/await
* callback-style
