### ISSUE TITLE
[Bug]: Unable to remove created pipeline step

### ISSUE THREAD

**Issue by brlipi** [devopness/devopness#815]
### Which Devopness module(s) are the source of the bug?

Devopness web app

### Expected behavior

Once I click on "Remove" on the pipeline step, the removal confirmation page should show up so I can remove it.

### What is actually happening?

Once I click on "Remove" on the pipeline step, the page either doesn't show and redirects back to the "Projects" page or shows very briefly and the redirects to the "Projects" page.

### Steps to reproduce

1. Go to an application you've created or have permissions to add steps to it's pipeline.
2. Click on "Details".
3. Click on the dropdown menu named "Settings".
4. Click on "Pipelines".
5. Choose a pipeline by clicking on it's corresponding "Details" button.
6. Click on "Steps".
7. If there are no previously created steps, create one.
8. Click on "Remove" on a created pipeline step.

### Additional details

This behavior has been reproduced in the browsers:

- Firefox 120.0
- Chromium 119.0.6045.199

**Comment by thlmenezes** [comment]
Hello @brlipi! 👋

This issue was fixed in the lastest update to Devopness web app

Thank you for reporting this issue 💖
