### ISSUE TITLE
[Bug]: `serverOptions` isn't been exposed in `StaticService` class

### ISSUE THREAD

**Issue by vianaz** [devopness/devopness#818]
### Which Devopness module(s) are the source of the bug?

SDK-JS

### SDK Version

2.115.0

### Expected behavior

As a SDK user, i expected that the `StaticService` class should have a `serverOptions` property 

### What is actually happening?

`StaticService` doesn't have a `serverOptions` property 

### Reproduction link

https://github.com/devopness/devopness/blob/7344938b224e461ce488e0496890389dc59baeab/packages/sdks/javascript/src/services/StaticService.ts#L13C1-L25C2

### Steps to reproduce

1. Instantiate `DevopnessApiClient`.
```js
const devopnessApi = new DevopnessApiClient({ baseURL: BASE_URL })
```
2. Try access `devopnessApi.static.serverOptions`
3. See that `serverOptions` property doesn't exists

**Comment by jfoliveira** [comment]
> can i take this issue?

@vianaz sure thing!
Feel free to submit a pull request.
Please reference this issue on the PR description.

**Comment by vianaz** [comment]
@jfoliveira PR merged :))
Should i close this issue? I don't see nothing about in [`CONTRIBUTING`
](https://github.com/devopness/devopness/blob/main/CONTRIBUTING.md)

**Comment by brlipi** [comment]
> @jfoliveira PR merged :)) Should i close this issue? In [`CONTRIBUTING`](https://github.com/devopness/devopness/blob/main/CONTRIBUTING.md) says that auto close this issue, but this doesn't happens

You apparently didn't follow the fourth step on [Making Changes and submitting Pull Requests](https://github.com/devopness/devopness/blob/main/CONTRIBUTING.md#making-changes-and-submitting-pull-requests) by adding the supported keyword in the PR's description. You can see the supported keywords [in the documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Perhaps a change to the Pull Request template could streamline this process?

**Comment by vianaz** [comment]
> Perhaps a change to the Pull Request template could streamline this process?

@brlipi yeah :)) In Pull Request template has something about [Jira issue](https://github.com/devopness/devopness/blob/dc4641ff79cc893742d50044c9de08411f72e267/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L5) and i don't have access to Jira, maybe should be changed to some like:

```
## Issues resolved by this PR
<!-- Check list box of Issues completed by this PR -->

- [ ] Closes #ISSUE-NUMBER
```

What do you think?

**Comment by jfoliveira** [comment]
> > Perhaps a change to the Pull Request template could streamline this process?
> 
> @brlipi yeah :)) In Pull Request template has something about [Jira issue](https://github.com/devopness/devopness/blob/dc4641ff79cc893742d50044c9de08411f72e267/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L5) and i don't have access to Jira, maybe should be changed to some like:
> 
> ```
> ## Issues resolved by this PR
> 
> 
> - [ ] Closes #ISSUE-NUMBER
> ```
> 
> What do you think?

@brlipi @vianaz 
Changes applied in https://github.com/devopness/devopness/pull/827
