### ISSUE TITLE
[Feature request]: add node js >= v18.17.0

### ISSUE THREAD

**Issue by andrelcb** [devopness/devopness#836]
### Describe the solution you'd like.

Today it only allows you to create an application with nodejs 12 or 16. Some applications like nextjs 14 only work on the latest version of nodejs

**Comment by jfoliveira** [comment]
Added support to Node.js 18 and 20, since January/2024. 🎉 

<img width="947" alt="image" src="https://github.com/devopness/devopness/assets/1943318/8d2f968f-5c27-44c3-b455-69e3a4e3fd20">
