### ISSUE TITLE
[Bug]: node.js dependency update

### ISSUE THREAD

**Issue by Hugollemos** [devopness/devopness#847]
### Problem: What is happening?

the pipeline is breaking because it doesn't find the version of node.js:16.16, but it is configured in the application as shown in the image.

![image](https://github.com/devopness/devopness/assets/72999426/fabf26d5-3246-4b08-a101-1c05cbaf03dc)

The error message below says that the version of node.js16.16 was not found, but it was configured correctly in the application.

![image_2024-01-10_142111385](https://github.com/devopness/devopness/assets/72999426/eb20a454-8f5f-4652-baa8-667db5a11add)

### Expected behavior

It was expected that the pipeline would find the node.js version and not break

### Steps to reproduce

CLICK ON IN THE TOP RIGHT CORNER ADD APPLICATION
FILL IN THE FIELDS OF YOUR SOURCE PROVIDER
CHOOSE THE NODEJS STACK
select engine version: 16.16
Define your repository's directory layout
Define build configuration
CLICK NEXT
RETURN TO APPLICATIONS PAGE
CLICK ON 'DEPLOY'
SELECT THE PERTINENT PIPELINE
CLICK ON RUN DEPLOY

see error when installing dependencies

### Which Devopness module(s) are the source of the bug?

Don't know / other

### Reproduction link

my link reproduction: https://app.devopness.com/actions/20803

**Comment by Silva97** [comment]
Thank you for your report @Hugollemos. We are investigating about this issue and will fix it as soon as possible.

**Comment by Silva97** [comment]
@Hugollemos this issue has been fixed. Feel free to reopen if needed.

Thank you for this bug report!
