### ISSUE TITLE
[Bug]: step in linked-resources documentation not exist anymore

### ISSUE THREAD

**Issue by guipontes7** [devopness/devopness#848]
### Problem: What is happening?

In _Linked-resources_ documentation (_Add a Linked Resource_ topic) have a step that needs be updated.

Step 5 says to click "...", but that button has been replaced by the "settings" button.
![devopness_issue_01](https://github.com/devopness/devopness/assets/95928171/ef7750fc-fc45-4c62-8d18-f0d84c100d48)

### Expected behavior

It is expected that step 5 will ask you to click on the "settings" button.

### Steps to reproduce

1. On Devopness, navigate to a project then select an environment
2. Find the Applications card
3. Click _View_ in the Applications card to see a list of existing _Applications_
4. Click _DETAILS_ on the application you want to link a server
5. On the upper-right corner of the application details view, click "_..._"

The "_..._" button does not exist.

### Which Devopness module(s) are the source of the bug?

Documentation

**Comment by jfoliveira** [comment]
Resolved by #851 
Thanks @guipontes7 for this bug report and for submitting a PR to fix it! 👏 ❤️
