### ISSUE TITLE
[Bug]: Many documentation articles not describing current UI/UX

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#855]
## Description

This issue aims to list all documentation articles that need to be reviewed after the recent updates in the web app have changed the user flows considerably

### Task List

- [x] #859
- [x] #860
- [x] #861
- [x] #862
- [x] #863
- [x] #864
- [x] #865
- [x] #858
- [x] #866
- [x] #867
- [x] #868
- [x] #869
- [x] #870
- [x] #871
- [x] #872
- [x] #873
- [x] #874
- [x] #875
- [x] #876
- [x] #877
- [x] #878
- [x] #879
- [x] #880
- [x] #856
- [x] #881
- [x] #882

### Details Button replaced with Details link

Pages that listed resources (e.g: Applications) had a button on labeled `DETAILS` to access a resource details page (e.g: Application Details), as mentioned in the article quoted below from the documentation available @ [Add a File](https://www.devopness.com/docs/files/add-file/)

> 4. In the list of applications find the application where you want to add a configuration file and click `DETAILS`

The `DETAILS` button was replaced by a link in the resource name column

#### Articles that need to be updated

All articles that guide the users to search for DETAILS button on the UI

### Linked Resources replaced with Tabs

A link between resources like Applications and Servers was managed using the Linked Resources page, this was replaced by adding tabs to the Application Details page; this way eliminating the concept of Linked Resources from the app

#### Articles that need to be updated

All articles related to Linked Resources, Configuration Files and Variables need to be updated

## Update Table

This table tracks all documentation articles and lists if the article is updated according to each category below:

- Details: Does this article guide users to the `DETAILS` link instead of the `DETAILS` button?
- Tabs: Does this article guide users to use the tabs instead of the linked resource, pipelines, variables, configuration files pages ?

And the column data can be one of the possibilities below:

1. An empty means the article is not affected by that change
2. An ❌ emoji means the article has an issue related to that change
3. An ✅ emoji means the article does not have an issue related to that change

| Article Name | Details | Tabs |
| :-- | :--: | :--: |
|[Deploy Application using an Incoming Hook](https://www.devopness.com/docs/applications/deploy-application-using-incoming-hook/) | ✅ ||
|[Edit an Application](https://www.devopness.com/docs/applications/edit-application/)| ✅||
|[Add a File](https://www.devopness.com/docs/files/add-file/)| ✅ | ✅|
|[Edit a File](https://www.devopness.com/docs/files/edit-file/)| ✅ | ✅|
|[Remove a File](https://www.devopness.com/docs/files/remove-file/)|✅|✅|
|[Add a Linked Resource](https://www.devopness.com/docs/linked-resources/add-linked-resource/)|✅|✅|
|[Remove a Network](https://www.devopness.com/docs/networks/remove-network/)|✅||
|[Add a Pipeline](https://www.devopness.com/docs/pipelines/add-pipeline/)|✅|✅|
|[Edit a Pipeline](https://www.devopness.com/docs/pipelines/edit-pipeline/)|✅|✅|
|[Remove a Pipeline](https://www.devopness.com/docs/pipelines/remove-pipeline/)|✅|✅|
|[Run a Pipeline](https://www.devopness.com/docs/pipelines/run-pipeline/)|✅|✅|
|[Add Step to Pipeline](https://www.devopness.com/docs/pipelines/steps/add-step/)|✅|✅|
|[Remove Step from Pipeline](https://www.devopness.com/docs/pipelines/steps/remove-step/)|✅|✅|
|[Check a Role's Permissions](https://www.devopness.com/docs/roles/view-role/)|✅||
|[Delete a Server provisioned by Devopness](https://www.devopness.com/docs/servers/delete-cloudprovider-server/)|✅||
|[Get a Server’s Status](https://www.devopness.com/docs/servers/get-server-status/)|✅||
|[Remove a Self Hosted Server](https://www.devopness.com/docs/servers/remove-selfhosted-server/)|✅||
|[Restart a Server](https://www.devopness.com/docs/servers/restart-server/)|✅||
|[Start a Server](https://www.devopness.com/docs/servers/start-server/)|✅||
|[Stop a Server](https://www.devopness.com/docs/servers/stop-server/)|✅||
|[Deploy SSH Key](https://www.devopness.com/docs/ssh-keys/deploy-ssh-key/)|✅||
|[Link an SSH Key to a Server](https://www.devopness.com/docs/ssh-keys/link-ssh-key/)|✅|✅|
|[Remove an SSH Key](https://www.devopness.com/docs/ssh-keys/remove-ssh-key/)|✅||
|[Add an SSL Certificate](https://www.devopness.com/docs/ssl-certificates/add-ssl-certificate/)|✅||
|[Add a Subnet](https://www.devopness.com/docs/subnets/add-subnet/)|✅||
|[Remove a Subnet](https://www.devopness.com/docs/subnets/remove-subnet/)|❌||

**Comment by anurag-compile** [comment]
assign to me

**Comment by thlmenezes** [comment]
Hello @anurag-compile, thanks for the interest in this issue.

I've assigned this issue to you, as requested; please note that this issue is composed of many tasks.

Feel free to tag me if this issue gets overwhelming, personally I'd recommend opening separated PRs for every task or resource type (Pipelines, Servers, ...)
