### ISSUE TITLE
[docs]: fix article "Add an SSL Certificate"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#856]
### Description

Article [Add an SSL Certificate](https://www.devopness.com/docs/ssl-certificates/add-ssl-certificate/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. Click DETAILS on the application you want to add an SSL certificate to
  ```
- [ ] Guide the user to find labels instead of icons
  - It is preferable to not have a UI dependency inside the documentation
  - The documentation, in the current state, will need an update for every icon change 
  ```
  1. On the upper-right corner click SSL (open lock icon)
  ```
- [ ] Guide the user on what action to expect when deploying an ssl certificate, similar to other articles that trigger actions
  - ❌ An action to install the SSL certificate will start
  - ✅ Wait for the ssl-certificate:deploy action to be completed

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
