### ISSUE TITLE
[docs]: fix article "Deploy Application using an Incoming Hook"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#859]
### Description

Article [Deploy Application using an Incoming Hook](https://www.devopness.com/docs/applications/deploy-application-using-incoming-hook/) needs to be updated, more details @ #855 

### Issue List

- [x] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of applications, find the application with the pipeline you want to manage and click DETAILS
  1. In the list of pipelines, find the pipeline you want to manage and click DETAILS
  1. Click DETAILS on the application you triggered the pipeline
  ```
- [x] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the applications details view click SETTINGS
  1. Use the drop-down menu to choose PIPELINES
  ```
- [ ] Update text to show <pipeline_id> as text
  - ❌ Steps to find the `` of an `application:deploy` pipeline
  - ✅ Steps to find the `pipeline_id` of an `application:deploy` pipeline

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
