### ISSUE TITLE
[docs]: fix article "Edit an Application"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#860]
### Description

Article [Edit an Application](https://www.devopness.com/docs/applications/edit-application/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. Click DETAILS on the application you want to edit
  ```

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
