### ISSUE TITLE
[docs]: fix article "Edit a File"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#862]
### Description

Article [Edit a File](https://www.devopness.com/docs/files/edit-file/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of applications find the application with the configuration file you want to edit and click DETAILS
  1. In the list of configuration files find the configuration file you want to edit and click DETAILS
  ```
- [ ] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the applications details view click SETTINGS
  1. Use the drop-down menu to choose CONFIGURATION FILES
  ```
- [ ] Use correct resource type name
  - ❌ On the upper-right corner of the key details, click EDIT
  - ✅ On the upper-right corner of the configuration file details, click EDIT

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
