### ISSUE TITLE
[docs]: fix article "Remove a File"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#863]
### Description

Article [Remove a File](https://www.devopness.com/docs/files/remove-file/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of applications, find the application with the configuration file you want to remove and click DETAILS
  1. In the list of configuration files, find the file you want to remove and click DETAILS
  ```
- [ ] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the applications details view, click SETTINGS
  1. Use the drop-down menu to choose CONFIGURATION FILES, to see a list of existing Configuration Files
  ```

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
