### ISSUE TITLE
[docs]: fix article "Remove a Network"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#865]
### Description

Article [Remove a Network](https://www.devopness.com/docs/networks/remove-network/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of networks, find the network you want to remove and click DETAILS
  ```

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
