### ISSUE TITLE
[docs]: fix article "Edit a Pipeline"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#866]
### Description

Article [Edit a Pipeline](https://www.devopness.com/docs/pipelines/edit-pipeline/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of applications find the application with the pipeline you want to edit and click DETAILS
  1. In the list of pipelines find the pipeline you want to edit and click DETAILS
  ```
- [ ] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the applications details view click SETTINGS
  1. Use the drop-down menu to choose PIPELINES
  ```

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
