### ISSUE TITLE
[docs]: fix article "Run a Pipeline"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#868]
### Description

Article [Run a Pipeline](https://www.devopness.com/docs/pipelines/run-pipeline/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. Click DETAILS on the network rule you want to run a pipeline
  ```
- [ ] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the network rule details view, click SETTINGS
  1. Use the drop-down menu to choose PIPELINES, to see a list of existing Pipelines
  ```
- [ ] Update action code to lowercase
  - ❌ Wait for the action Network-rule:Deploy to be completed
  - ✅ Wait for the action network-rule:deploy to be completed

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
