### ISSUE TITLE
[docs]: fix article "Check a Role's Permissions"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#871]
### Description

Article [Check a Role's Permissions](https://www.devopness.com/docs/roles/view-role/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of Roles find the Role you want to check the permissions and click DETAILS
  ```

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
