### ISSUE TITLE
[docs]: fix article "Delete a Server provisioned by Devopness"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#872]
### Description

Article [Delete a Server provisioned by Devopness](https://www.devopness.com/docs/servers/delete-cloudprovider-server/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of servers, find the server you want to delete and click DETAILS
  ```

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
