### ISSUE TITLE
[docs]: fix article "Remove a Self Hosted Server"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#874]
### Description

Article [Remove a Self Hosted Server](https://www.devopness.com/docs/servers/remove-selfhosted-server/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of servers, find the server you want to remove and click DETAILS
  ```

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
