### ISSUE TITLE
[docs]: fix article "Start a Server"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#876]
### Description

Article [Start a Server](https://www.devopness.com/docs/servers/start-server/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of servers, find the server you want to start and click DETAILS
  ```
- [ ] Update action code to lowercase
  - ❌ Wait for the Server:start action to be completed
  - ✅ Wait for the server:start action to be completed

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
