### ISSUE TITLE
[docs]: fix article "Stop a Server"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#877]
### Description

Article [Stop a Server](https://www.devopness.com/docs/servers/stop-server/) needs to be updated, more details @ #855 

### Issue List

- [ ] Update public IP address note to warning
- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of servers, find the server you want to stop and click DETAILS
  ```
- [ ] Update action code to lowercase
  - ❌ Wait for the Server:stop action to be completed
  - ✅ Wait for the server:stop action to be completed

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?

**Comment by dudunog** [comment]
@thlmenezes Is there an example of a warning note? I didn't find.

**Comment by thlmenezes** [comment]
@dudunog no, this article will be the first example.

To use a warning callout, follow the pattern below:

```md
{% warning %} 
 
**WARNING**: <message>
  
{% endwarning %}
```

**Comment by dudunog** [comment]
> @dudunog no, this article will be the first example.
> 
> To use a warning callout, follow the pattern below:
> 
> ```
> {% warning %} 
>  
> **WARNING**: <message>
>   
> {% endwarning %}
> ```

Thanks!
