### ISSUE TITLE
[docs]: fix article "Deploy SSH Key"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#878]
### Description

Article [Deploy SSH Key](https://www.devopness.com/docs/ssh-keys/deploy-ssh-key/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. Click DETAILS on the SSH key you want to deploy
  ```
- [ ] Update action code to lowercase
  - ❌ Wait for the Ssh-key:Deploy action to be completed
  - ✅ Wait for the ssh-key:deploy action to be completed

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
