### ISSUE TITLE
[docs]: fix article "Link an SSH Key to a Server"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#879]
### Description

Article [Link an SSH Key to a Server](https://www.devopness.com/docs/ssh-keys/link-ssh-key/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. Click DETAILS on the SSH key you want to link to a server
  ```
- [ ] Guide the user to use Tabs
  - Steps below needs to be fixed accordingly
  ```
  1. On the upper-right corner of the SSH key details view, click SETTINGS
  1. Use the drop-down menu to choose Linked resources
  1. On the upper-right corner of the Linked resources list, click LINK TO
  1. Use the drop-down menu to choose Servers
  1. Follow the prompts then click Link
  1. In the Linked Resource list, the recently linked server can be seen in the DEPENDS ON table
  ```

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?
