### ISSUE TITLE
[docs]: fix article "Add a Subnet"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#881]
### Description

Article [Add a Subnet](https://www.devopness.com/docs/subnets/add-subnet/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of networks, find the network you want to manage and click DETAILS
  ```

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by dudunog** [comment]
@thlmenezes can you assign this to me?

**Comment by dudunog** [comment]
@thlmenezes I need to to sign the Contributor License Agreement, can you help me?

**Comment by thlmenezes** [comment]
@dudunog I've assigned this issue to you, as requested.

Happy contributing 😄

**Comment by jfoliveira** [comment]
> @thlmenezes I need to to sign the Contributor License Agreement, can you help me?

@dudunog your user is now authorized to submit PRs to this repo.
Once you update your PR and fix all pending CI checks, it will be reviewed.
