### ISSUE TITLE
[docs]: fix article "Remove a Subnet"

### ISSUE THREAD

**Issue by thlmenezes** [devopness/devopness#882]
### Description

Article [Remove a Subnet](https://www.devopness.com/docs/subnets/remove-subnet/) needs to be updated, more details @ #855 

### Issue List

- [ ] Guide the user to click Resource Name
  - Steps below needs to be fixed accordingly
  ```
  1. In the list of networks, find the network with the subnet you want to remove and click DETAILS
  1. In the list of subnets, find the subnet you want to remove and click DETAILS
  ```

**Comment by thlmenezes** [comment]
This issue remains relevant to documentation

**Comment by thlmenezes** [comment]
@anurag-compile I've assigned this issue to you, as requested.

Happy contributing 😄

**Comment by thlmenezes** [comment]
> please explain little bit like exactly what is required?

@anurag-compile, this article uses an outdated instruction to guide users to access the "Resource Details" page; this issue goal is to update the article to guide the user in the new UI.

We currently have the article [Add a Pipeline](https://www.devopness.com/docs/pipelines/add-pipeline/) as a reference of the new UI instructions, please use it as a guideline on how to modify this article

More information on the UI changes in #855

> ### Details Button replaced with Details link
> Pages that listed resources (e.g: Applications) had a button on labeled DETAILS to access a resource details page (e.g: Application Details), as mentioned in the article quoted below from the documentation available @ [Add a File](https://www.devopness.com/docs/files/add-file/)

**Comment by jfoliveira** [comment]
@anurag-compile it's simple if you sign up to Devopness at https://www.devopness.com/ and see the documentation page being loaded when clicking on the ❓ button.

You haven't used Devopness yet, am I right?

**Comment by thlmenezes** [comment]
@anurag-compile I'm reopening this issue, as it is still a relevant issue for our documentation.

Let me know if there's anything me or the team can do to help you in resolving this issue
