### ISSUE TITLE
[Bug]: `Internal Server Error` when trying to deploy a `Daemon` without a working directory

### ISSUE THREAD

**Issue by rodrigomolter** [devopness/devopness#973]
### Problem: What is happening?

When configuring a new Daemon trough the **WebApp**, in the step `02 - Configure Daemon directory` it defines the working directory where the command will be executed, relative to the Application directory.

![Configure Daemon Directory Step](https://github.com/user-attachments/assets/fad0ec4a-87df-4434-8d3c-94f3531c73fa)

The `Working Directory` is said as **Optional** if you set-up an Application.

But what happens is if you don't setup any directory (leaving the input empty), you will receive a `Server Error` message when trying to deploy that Daemon without any feedback of why it is happening.

![Server Error when deploying Daemon](https://github.com/user-attachments/assets/6a3aea3d-629f-46cf-8cd2-b69e5167c0e9)

### Expected behavior

The `Working directory` should really be optional and give user a better feedback of what is happenning.

### Steps to reproduce

> [!NOTE]
> For reproduce this, you will need a running `server` and `application` on your environment.
> See [Add a server](https://www.devopness.com/docs/servers/add-server/) and [Add an Application](https://www.devopness.com/docs/applications/add-application/) on Devopness Docs. 

## Steps
1. Go to the environment resources page
2. Click the `Daemons` card
3. On the upper-right corner click `ADD DAEMON`
4. Fill your Daemon details, e.g.:
  - Name: `no_wd_daemon`
  - Command: `echo test`
5. Click `NEXT` button
6. In `Application` select your application
7. Leave the `Working Directory` empty.
8. Click `NEXT` button
9. Click `CONFIRM` button
10. In the upper-left select the `Servers` tab
11. Click `LINK SERVER` button
12. Select your server in the dropdown list
13. Click `CONFIRM` button
14. On the upper-right, click the `DEPLOY` button
15. In the Pipeline dropdown, select the `DEPLOY` pipeline
16. Click `NEXT` button
17. Click `DEPLOY` button
18. See the error occours, without an obvious feedback why it's happenning.

### Which Devopness module(s) are the source of the bug?

Devopness web app

### Additional details

- Browser: Brave [Version 1.68.137 Chromium: 127.0.6533.100]
- Cloud Provider: Google Cloud Plataform

**Comment by Diegiwg** [comment]
Thank you very much @rodrigomolter for reporting.

BUG fixed and deployed to production.
